#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 26 04:49:14 2020

@author: hm
"""

import tkinter
from tkinter import ttk

from PIL import Image, ImageTk
from tkinter.ttk import *

# from PIL.Image import core as _imaging
# https://www.youtube.com/watch?v=5ZgW4sQdAgQ

# import tkFont
# font = tkFont.Font ( option, ... )

root = tkinter.Tk(className='Play_a_game_of_Pig')
root.iconbitmap('pig.ico')
# set window size
root.geometry("1000x800")


# RosyBrown colored box at top
top_frame = tkinter.Frame(root, borderwidth=5)
top_frame = tkinter.Frame(root, width=300, height=370, background="RosyBrown1")
top_frame.grid(row=0, column=0, rowspan=3, columnspan=2, padx=(20, 20))
# Give the frame a border
# top_frame.config(highlightbackground="black", highlightcolor="black", highlightthickness=1)

# set window color
root.configure(bg='LightPink3')

# myLabel00 = tkinter.Label(root, text=' \t \t   ', bg="RosyBrown1")
# myLabel00.grid(row=0, column=0, columnspan=2)

# Change the label to being attatched to the top_frame, not the root widget
# myLabel0 = tkinter.Label(root, text='  I am fond of pigs. ')
myLabel0 = tkinter.Label(top_frame, text='\n \n  I am fond of pigs.  \n', bg="RosyBrown1")
myLabel0.config(font=("Courier", 10))
myLabel0.grid(row=1, column=0)

myLabel5 = tkinter.Label(top_frame, text='  Dogs look up to us.  \n', bg="RosyBrown1")
myLabel5.config(font=("Courier", 10))
myLabel5.grid(row=2, column=0)

myLabel5 = tkinter.Label(top_frame, text='  Cats look down on us.  \n ', bg="RosyBrown1")
myLabel5.config(font=("Courier", 10))
myLabel5.grid(row=4, column=0)

myLabel5 = tkinter.Label(top_frame, text='  Pigs treat us as equals.  \n', bg="RosyBrown1")
myLabel5.config(font=("Courier", 10))
myLabel5.grid(row=5, column=0)

myLabel5 = tkinter.Label(top_frame, text='    ― Winston S. Churchill  \n \n \n \n ', bg="RosyBrown1")
myLabel5.config(font=("Courier", 10))
myLabel5.grid(row=6, column=0)

myLabel1 = tkinter.Label(root, text='  Please enter number of players: ', background="mistyRose")
myLabel1.config(font='Courier 14 bold')
myLabel1.grid(row=2, column=0, rowspan=2, columnspan=2)

e = tkinter.Entry(root, width=5, borderwidth=5)
e.grid(row=2, column=3, rowspan=2)


def myClick():
    myLabel3 = tkinter.Label(root, text=' pigs pigs pigs', background="pink")
    myLabel3.grid(row=4, column=3)

def myGameInstructionsButton():
    bottom_frame = tkinter.Frame(root, borderwidth=5)
    bottom_frame = tkinter.Frame(root, width=300, height=600, background="Pink")
    bottom_frame.grid(row=6, column=0, rowspan=5, columnspan=2, padx=(40, 40))
    bottom_frame.config(highlightbackground="black", highlightcolor="black", highlightthickness=5)
    # myfont_01 = tkFont.font(family='Courier', size=10, weight='bold', color="black")  
    # import tkFont
    #font = tkFont.Font ( option, ... )

    # Game Instructions
    game_Instructions_text_0 = '\nGame Rules: \n '
    myLabel6 = tkinter.Label(bottom_frame, background="pink", fg="black", text=game_Instructions_text_0)
    myLabel6.config(font='Courier 16 bold') 
    game_Instruction_text_1 = ' \n - Player with most points wins. \n \n - In a tie, the first player looses. \n'
    game_Instruction_text_2 =  game_Instruction_text_1 + '\n - Roll a 1 = lose points that turn. \n \n - Roll two 1s = lose ALL game points. \n'
    myLabel2 = tkinter.Label(bottom_frame, background="pink", fg="black", text=game_Instruction_text_2)
    myLabel2.config(font='Courier 14')  

    print(game_Instruction_text_2)
    
    myLabel6.grid(row=3, column=0)
    myLabel2.grid(row=4, column=0)
    
    buttonForget = ttk.Button(bottom_frame,
                          text = 'Close Rules',
                          command=lambda: [bottom_frame.grid_forget(), myInstructionsButton.grid(row=11, column=0)])
    # multiple commands inside a lambda: 
    # command=lambda:[funcA(), funcB(), funcC()]
    # grid() is the oppostie of .grid_forget(). It makes it remember.
    
    buttonForget.grid(row=5, column=0)
    
    myInstructionsButton.grid_forget()

    # tkinter.messagebox.showinfo(bottom_frame, 'Game Rules:',
    #                             '- Player with most points wins. \n',
    #                             '- In a tie, the first player looses.\n',
    #                             '- Roll a 1 = lose points that turn.\n',
    #                             '- Roll two 1s = lose ALL game points.\n')
    # bottom_frame.deiconify()
    # bottom_frame.quit()
    # bottom_frame.destroy()
    
                                 
    # myLabel2.grid(row=4, column=0)
    # myLabel2.config(font='Courier 12 bold')
# This button should show this frame when clicked: bottom_frame
# https://www.delftstack.com/howto/python-tkinter/how-to-hide-recover-and-delete-tkinter-widgets/


# This button was previously a tkinter.Button, but ttk.Button offers highlighting during mouse hover.
myButton = ttk.Button(root, text="Next", width=10, command=myClick)
myButton.grid(row=3, column=3)

myInstructionsButton = ttk.Button(root, text="Show game rules", command=myGameInstructionsButton)
myInstructionsButton.grid(row=11, column=0)

# There is a Spyder bug that makes the window hang up on root.destroy
# https://stackoverflow.com/questions/54271907/tkinter-destroy-and-quit-freezes-root-window-on-mac
myQuitButton = ttk.Button(root, text="Quit game", command=root.destroy)
myQuitButton.grid(row=11, column=1)

try:
    img = ImageTk.PhotoImage(Image.open("manRidesPig.png"))
    myLabel4 = tkinter.Label(image=img)
    myLabel4.grid(row=1, column=4, columnspan=3, rowspan=10, padx=(20, 20))
except IOError:
    pass

assert isinstance(img, ImageTk.PhotoImage)

# Pink box at bottom of screen displays rules
# This is way too much code usinf a Label.
# I actually want to use a Message widget to display multiline text.

# MOVED INTO BUTTON F(x)
# bottom_frame = tkinter.Frame(root, borderwidth=5)
# bottom_frame = tkinter.Frame(root, width=300, height=300, background="Pink")
# bottom_frame.grid(row=6, column=0, rowspan=5, columnspan=2, padx=(20, 20))
# Give the frame a black border
# bottom_frame.config(highlightbackground="black", highlightcolor="black", highlightthickness=1)

# Game Instructions
# myLabel2 = tkinter.Label(bottom_frame, text='  Game Rules: ', background="pink")
# myLabel2.grid(row=4, column=0)
# myLabel2.config(font='Courier 12 bold')

# myLabel6 = tkinter.Label(bottom_frame, text=' - Player with most points wins. ', background="pink")
# myLabel6.grid(row=5, column=0)
# myLabel6.config(font='Courier 10 bold')

# myLabel7 = tkinter.Label(bottom_frame, text=' - In a tie, the first player looses. ', background="pink")
# myLabel7.grid(row=6, column=0)
# myLabel7.config(font='Courier 10 bold')

# myLabel8 = tkinter.Label(bottom_frame, text=' - Roll a 1 = lose points that turn. ', background="pink")
# myLabel8.grid(row=7, column=0)
# myLabel8.config(font='Courier 10 bold')

# myLabel9 = tkinter.Label(bottom_frame, text=' - Roll two 1s = lose ALL game points. ', background="pink")
# myLabel9.grid(row=8, column=0)
# myLabel9.config(font='Courier 10 bold')

root.mainloop()
